//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 09/10/2020 17:32:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace EnsekCore
{
    public partial class User {

        public User()
        {
            this.MeterReadings = new List<MeterReading>();
            OnCreated();
        }

        public virtual int AccountId { get; set; }

        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual IList<MeterReading> MeterReadings { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
