//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 09/10/2020 17:32:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace EnsekCore
{
    public partial class MeterReading {

        public MeterReading()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int AccountId { get; set; }

        public virtual string MeterReadingDateTime { get; set; }

        public virtual string MeterReadValue { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
